version: "3.5"
services:
  api:
    container_name: sopick_api
    build:
      context: ./
      dockerfile: ./etc/docker/api/Dockerfile
    restart: on-failure
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api/src:/app
      - bundle:/bundle:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3031:3000
    depends_on:
      - db
  db:
    container_name: sopick_db
    build:
      context: ./
      dockerfile: ./etc/docker/db/Dockerfile
    volumes:
      - "./etc/docker/db/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3033:3306"
  swagger:
    container_name: sopick_swagger
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/api/swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      API_URL: swagger.yaml
    ports:
      - "3039:8080"

volumes:
  bundle:
