default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV.fetch('MYSQL_HOST') { "" } %>
  # host: db

development:
  <<: *default
  database: sopick_development

test:
  <<: *default
  database: sopick_test

production:
  <<: *default
  database: sopick_production
  username: root
  password: <%= ENV['SOPICK_DATABASE_PASSWORD'] %>
